### ISSUE TITLE
Work and section pages are cut off on the bottom on mobile

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/Sailfish#33]
This is likely due to the header sticking to the top when scrolling, meaning you can't scroll down far enough to see the rest.

**Comment by Figments** [comment]
this no longer happens on my phone, but i'll keep this open in case someone else raises a similar issue (like on Android)

**Comment by Figments** [comment]
closing this for now. will reopen if someone raises a similar issue
