### ISSUE TITLE
Process for creating and submitting fic is confusing for new users

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/Sailfish#41]
Current pain points for creating and submitting a fic:
1. Knowing that Long Description isn't where you put the full story / first chapter
2. After creating a chapter, knowing how to publish it
3. Knowing how to submit a fic and that you need to publish chapters first

**Comment by Figments** [comment]
all of this is now made more obvious on work pages (publish has its own obvious button, and includes a prompt explaining how to submit to the queue and what to expect/look out for). closing this for now, but we'll see if this is still a big issue in the future.
