### ISSUE TITLE
Bookshelves don't load

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/Sailfish#48]
https://offprint.net/profile/IQ3lL4j-V/shelf/0WOg95e8cxZMk2x4IshVL

The works in this and other shelves don't load. This applies to your own shelves and those of other users.

This is related to the fact that content is displayed using the _id value, when in fact it should use the content value.

Premade library shelves like "Prose & Poetry" load fine.

**Comment by Figments** [comment]
works load correctly now
