### ISSUE TITLE
Add Anthology genre

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/Sailfish#55]
User request

My comment:
About anthology, there was some debate earlier how to handle it, tied to a "series" feature we were planning that would allow you to display connected works together. However, given we haven't implemented that yet and I don't see any indication we will soon, I do agree an Anthology tag is warranted. Though I was arguing in favor of that even with series implemented.

**Comment by Figments** [comment]
added as a work kind in alpha.10
