### ISSUE TITLE
Keep track of number of works of each genre

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/Sailfish#65]
Related to OffprintStudios/dragonfish#737 , we should keep track of the number of works of each genre, for display on the Browse genre page.
However, genres don't already have a table, so we'll have to figure out how best to handle this.

**Comment by Figments** [comment]
1.0.0-alpha.10 transitioned genres into "just another tag" like fandoms, and therefore this is now reflected on the client side.
