### ISSUE TITLE
Implement ability to re-submit rejected work; address multiple submission issue

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/Sailfish#78]
Currently, if a work is rejected, there is no mechanism by which a user can submit it again for mod approval.

EDIT: Just heard from another user that this happened to them too, on or around August 24th -- a work was duplicated on submission to the approval queue; when the works approver ran across it, they rejected one and approved the other, but that resulted in the work being rejected -- so really in addition to Issue 639 Sigma filed to allow users to resubmit rejected works after corrections, we also need the submission process to check for/prevent having the same work be submitted multiple times simultaneously?

**Comment by Figments** [comment]
submissions to the approval queue check for existing entries and increment an `attempts` value that cannot exceed 3 before permanently-rejecting a story. we can also add a `UNIQUE` constraint on `approval_queue.work_id` to enforce single-entries at the database level
