### ISSUE TITLE
Increase character limit for work and section titles

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/Sailfish#83]
I determined that one fanfic title that works on FimFiction doesn't work on Offprint. If people on FimFiction intend to import their fics to Offprint, we shouldn't force them to shorten their titles.

The title is The Great And Powerful Trixie Presents: The Great And Powerful Trixie Story: Starring Trixie, The Great And Powerful!

**Comment by Figments** [comment]
section and work titles have a maximum of 120 characters as of alpha.10, which should be more than sufficient (and even allows the example title to pass)
