### ISSUE TITLE
Notifications update sporadically

### ISSUE THREAD

**Issue by SigmasonicX** [OffprintStudios/Sailfish#96]
One user reported that they didn't get any notifications for stories they got comments on. When I left a test comment, they got all notifications for previous comments, but there wasn't a notification for the new comment.

Test comment was on
https://offprint.net/prose/6bzlrBWrg/the-birthday-cake

**Comment by Figments** [comment]
this should no longer happen, but we'll wait and see

**Comment by Figments** [comment]
i haven't seen any issue with notifications not popping when they're supposed to, so i'll consider this issue closed
